install:
  - choco install -y mingw -params "/threads:win32"
  - choco install -y cmake
  - gcc -v
  - ps: Start-FileDownload 'https://static.rust-lang.org/dist/rust-nightly-i686-pc-windows-gnu.exe'
  - rust-nightly-i686-pc-windows-gnu.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - rustc -V
  - cargo -V
  - git submodule update --init --recursive

build: false

test_script:
  - cargo test --verbose
  - cargo test --verbose --manifest-path=git2-curl/Cargo.toml
